#!/bin/bash -e

if [ -z "$TIMEOUT" ] ; then
    TIMEOUT=14400 # 4 hours
fi

set +e

remove_images() {
  while true
  do
    echo "Cleaning host..."
    docker rm $(docker ps -a -q)
    docker rmi $(docker images | grep -vE '(none|gregory90/nodejs|gregory90/php|gregory90/golang)' | awk '{print $3}')
    echo "Sleeping..."
    sleep $TIMEOUT
  done
}

remove_images

wait
