#!/bin/bash -e

if [ -z "$TIMEOUT" ] ; then
    TIMEOUT=86400
fi

set +e

remove_images() {
  while true
  do
    echo "Cleaning host"
    docker rm $(docker ps -a -q)
    docker rmi $(docker images -q) 

    echo "Sleep"
    sleep $TIMEOUT
  done
}

remove_images

wait
